# Generated by Django 4.2.28 on 2026-03-02 06:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(blank=True, db_index=True, help_text='Vendor / supplier name (auto-extracted or manual).', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total invoice amount (non-negative).', max_digits=12)),
                ('date', models.DateField(blank=True, db_index=True, help_text='Invoice date (parsed from raw text or entered manually).', null=True)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Supplies', 'Supplies'), ('Utilities', 'Utilities'), ('Professional Services', 'Professional Services'), ('Food & Beverage', 'Food & Beverage'), ('Rent', 'Rent'), ('Insurance', 'Insurance'), ('Marketing', 'Marketing'), ('Software & SaaS', 'Software & SaaS'), ('Hardware', 'Hardware'), ('Telecom', 'Telecom'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], default='Other', help_text='Expense category.', max_length=50)),
                ('currency', models.CharField(default='INR', help_text='ISO 4217 currency code.', max_length=3)),
                ('raw_text', models.TextField(help_text='Paste the raw invoice text here for AI extraction.')),
                ('parsed_by_ai', models.BooleanField(default=False, help_text='True if fields were set by AI extraction.')),
                ('ai_confidence', models.FloatField(blank=True, help_text='Confidence score from AI (0.0–1.0).', null=True)),
                ('ai_response', models.JSONField(blank=True, help_text='Raw AI response stored for audit trail.', null=True)),
                ('parsing_error', models.TextField(blank=True, help_text='Error details if AI parsing failed.')),
                ('parsed_at', models.DateTimeField(blank=True, help_text='Timestamp of last successful parse.', null=True)),
                ('parsed_attempts', models.PositiveIntegerField(default=0, help_text='Count of parse attempts (for idempotency).')),
                ('content_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of raw_text for dedup.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vendor_name', 'date'], name='idx_vendor_date'), models.Index(fields=['category'], name='idx_category'), models.Index(fields=['parsed_by_ai'], name='idx_parsed_by_ai')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('AI_PARSED', 'AI Parsed'), ('AI_FAILED', 'AI Failed'), ('FALLBACK_PARSED', 'Fallback Parsed'), ('MANUAL_EDIT', 'Manual Edit'), ('AI_ACCEPTED', 'AI Accepted'), ('AI_REJECTED', 'AI Rejected'), ('REPARSE_TRIGGERED', 'Re-parse Triggered'), ('DELETED', 'Deleted')], max_length=50)),
                ('actor', models.CharField(default='system', help_text="Username or 'system' for automated actions.", max_length=150)),
                ('details', models.JSONField(blank=True, help_text='Snapshot of changed fields / AI response summary.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
